name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  
  check-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Version
        run: docker --version
      
